import test from 'node:test';import assert from 'node:assert/strict';
import {createFirestoreAccess,firestoreMessage} from '../js/firestore-access.mjs';
function fixture(){let calls=0,time=1000,failure=null,resolve;const api={queryEqual:(a,b)=>a.path===b.path,refEqual:(a,b)=>a.path===b.path,getDocs:async r=>{calls++;if(failure)throw failure;return {path:r.path};},getDoc:async r=>{calls++;return {path:r.path};}};return {access:createFirestoreAccess(api,{now:()=>time}),api,count:()=>calls,tick:n=>time+=n,fail:err=>failure=err};}
test('Consulta equivalente y simultánea usa una sola lectura; expira al minuto',async()=>{const f=fixture();await Promise.all([f.access.getDocs({path:'asistencias'}),f.access.getDocs({path:'asistencias'})]);assert.equal(f.count(),1);await f.access.getDocs({path:'asistencias'});assert.equal(f.count(),1);f.tick(60001);await f.access.getDocs({path:'asistencias'});assert.equal(f.count(),2);});
test('Invalidar después de escritura y cambiar usuario obliga a renovar',async()=>{const f=fixture();await f.access.getDoc({path:'usuarios/a'});f.access.clear();await f.access.getDoc({path:'usuarios/a'});f.access.reset();await f.access.getDoc({path:'usuarios/a'});assert.equal(f.count(),3);});
test('429 pausa consultas nuevas sin reintentar en bucle y permite caché válida',async()=>{const f=fixture();await f.access.getDocs({path:'practicas'});f.fail({code:'resource-exhausted'});await assert.rejects(f.access.getDocs({path:'asistencias'}));await assert.rejects(f.access.getDocs({path:'alumnos'}));assert.equal(f.count(),2);await f.access.getDocs({path:'practicas'});assert.equal(f.count(),2);f.tick(60001);await assert.rejects(f.access.getDocs({path:'alumnos'}));assert.equal(f.count(),3);assert.match(firestoreMessage({code:'firestore/resource-exhausted'}),/No se perdió tu cuenta/);});
test('Una respuesta iniciada antes de invalidar no repuebla la caché',async()=>{const f=fixture();let done;f.api.getDocs=()=>new Promise(r=>done=r);const pending=f.access.getDocs({path:'practicas'});await Promise.resolve();f.access.clear();done('viejo');await pending;f.api.getDocs=async()=> 'nuevo';assert.equal(await f.access.getDocs({path:'practicas'}),'nuevo');});
test('Fallo de permisos no se conserva como respuesta ni activa pausa de cuota',async()=>{const f=fixture();f.fail({code:'permission-denied'});await assert.rejects(f.access.getDocs({path:'practicas'}));f.fail(null);await f.access.getDocs({path:'practicas'});assert.equal(f.count(),2);});

test('Un documento recibido en un listado se reutiliza al abrir su ficha',async()=>{let calls=0;const snap={ref:{path:'alumnos/a'},id:'a'},a=createFirestoreAccess({queryEqual:(a,b)=>a.path===b.path,refEqual:(a,b)=>a.path===b.path,getDocs:async()=>{calls++;return {docs:[snap]};},getDoc:async()=>{calls++;return snap;}});await a.getDocs({path:'alumnos'});assert.equal(await a.getDoc({path:'alumnos/a'}),snap);assert.equal(calls,1);assert.equal(await a.cachedDoc({path:'alumnos/a'}),snap);a.clear();assert.equal(a.cachedDoc({path:'alumnos/a'}),null);await a.getDoc({path:'alumnos/a'});assert.equal(calls,2);});

test('Una consulta histórica grande conserva su caché sin sembrar cientos de fichas',async()=>{let calls=0;const api={queryEqual:(a,b)=>a.path===b.path,refEqual:(a,b)=>a.path===b.path,getDocs:async()=>{calls++;return {docs:Array.from({length:1000},(_,id)=>({id,ref:{path:'practicas/'+id}}))};},getDoc:async()=>{}};const a=createFirestoreAccess(api);await a.getDocs({path:'practicas'});await a.getDocs({path:'practicas'});assert.equal(calls,1);});
