import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {JSDOM} from 'jsdom';
const html=fs.readFileSync('index.html','utf8');const dom=new JSDOM(html,{url:'http://localhost/'}),window=dom.window;
const store=new Map([['usuarios/admin',{rol:'admin',nombre:'Tutor'}],['alumnos/a',{nombre:'Melissa',apellido:'Barbeito',legajo:'123',email:'melissa@example.com'}],['practicas/p',{alumnoId:'a',lugar:'ULP',sector:'Helpdesk',tipo:'externa',fecha:'2026-09-28',fechaFin:'2026-09-30',diasSemana:[1,2,3],horasPorDia:5,horaInicio:'08:00',horaFin:'13:00',modoHoras:'jornadas',estado:'programada'}],['lugares/ulp',{nombre:'ULP'}]]);
const ref=(...args)=>({path:args.slice(1).join('/'),id:String(args.at(-1))});
const snapshot=r=>({id:r.id,ref:r,exists:()=>store.has(r.path),data:()=>store.get(r.path)});
let docFailure=null;const readQueries=[];
function queryDocs(r){
 readQueries.push(r);let docs=[...store.keys()].filter(k=>k.startsWith(r.path+'/')&&k.split('/').length===2).map(k=>snapshot({path:k,id:k.split('/')[1]}));
 const filters=r.filters||[],get=(d,f)=>f==='__name__'?d.id:d.data()[f];
 for(const f of filters.filter(f=>f.where)){const [key,op,value]=f.where;docs=docs.filter(d=>{const v=get(d,key);if(v===undefined)return false;return op==='=='?v===value:op==='in'?value.includes(v):op==='>='?v>=value:op==='<='?v<=value:op==='>'?v>value:op==='<'?v<value:false;});}
 const orders=filters.filter(f=>f.order).map(f=>f.order);const compare=(a,b)=>{for(const [key,dir]of orders){const av=get(a,key),bv=get(b,key);if(av!==bv)return (av<bv?-1:1)*(dir==='desc'?-1:1);}return (a.id<b.id?-1:a.id>b.id?1:0)*(orders.at(-1)?.[1]==='desc'?-1:1);};
 docs=docs.filter(d=>orders.every(([key])=>get(d,key)!==undefined)).sort(compare);
 const after=filters.find(f=>f.after);if(after)docs=docs.filter(d=>compare(d,after.after)>0);const cap=filters.find(f=>f.limit);if(cap)docs=docs.slice(0,cap.limit);return {docs};
}
const fsMock={queryEqual:(a,b)=>JSON.stringify(a)===JSON.stringify(b),refEqual:(a,b)=>a.path===b.path,getFirestore:()=>({}),collection:ref,doc:ref,documentId:()=> '__name__',startAfter:s=>({after:s}),where:(...x)=>({where:x}),orderBy:(...x)=>({order:x}),limit:n=>({limit:n}),query:(r,...filters)=>({...r,filters}),getDoc:async r=>{if(docFailure)throw docFailure;return snapshot(r);},getDocs:async r=>queryDocs(r),setDoc:async(r,d,opt)=>store.set(r.path,opt?.merge?{...store.get(r.path),...d}:d),updateDoc:async(r,d)=>store.set(r.path,{...store.get(r.path),...d}),deleteDoc:async r=>store.delete(r.path),addDoc:async(r,d)=>{const id='added'+store.size,n={path:r.path+'/'+id,id};store.set(n.path,d);return n;}};

fsMock.runTransaction=async(_,fn)=>fn({get:fsMock.getDoc,set:(r,d)=>store.set(r.path,d),update:(r,d)=>store.set(r.path,{...store.get(r.path),...d})});
fsMock.writeBatch=()=>{const ops=[];return {update:(r,d)=>ops.push(()=>fsMock.updateDoc(r,d)),set:(r,d)=>ops.push(()=>fsMock.setDoc(r,d)),commit:async()=>{for(const op of ops)await op();}};};
let authCb,errors=[],transactionCalls=0;const originalTransaction=fsMock.runTransaction;fsMock.runTransaction=(...args)=>{transactionCalls++;return originalTransaction(...args);};const context=vm.createContext({window,document:window.document,console,MutationObserver:window.MutationObserver,FileReader:window.FileReader,URL,Intl,Date:class extends Date{constructor(...args){super(...(args.length?args:['2026-09-29T17:00:00Z']));}static now(){return new Date('2026-09-29T17:00:00Z').getTime();}},setTimeout,clearTimeout,setInterval:()=>0,confirm:()=>true,prompt:()=>null,bootstrap:{Modal:{getOrCreateInstance:()=>({show(){}}),getInstance:()=>({hide(){}})}},alert:()=>{}});
context.bootstrap=context.bootstrap;context.window.bootstrap=context.bootstrap;
const cache=new Map();const make=(id,exports)=>new vm.SyntheticModule(Object.keys(exports),function(){for(const [k,v]of Object.entries(exports))this.setExport(k,v)},{context,identifier:id});
async function load(id){if(cache.has(id))return cache.get(id);let mod;
if(id.includes('firebase-firestore.js'))mod=make(id,fsMock);
else if(id.includes('firebase-auth.js'))mod=make(id,{getAuth:()=>({}),signInWithEmailAndPassword:async()=>{},signOut:async()=>{},onAuthStateChanged:(_,cb)=>authCb=cb});
else if(id.includes('firebase-app.js'))mod=make(id,{initializeApp:()=>({})});
else if(id.includes('firebase-functions.js'))mod=make(id,{getFunctions:()=>({}),httpsCallable:()=>async()=>({data:{listos:0,bloqueados:1,config:{horaEnvio:'08:00',zona:'America/Argentina/San_Luis'},detalles:[{lugar:'ULP',sector:'Helpdesk',estado:'bloqueado',detalle:'Falta PDF'}]}})});
else mod=new vm.SourceTextModule(fs.readFileSync(id,'utf8')+(id.endsWith('/app.js')?'\nexport {procesarFilasImportar, filasImportar,guardarPracticaConInformes};':''),{context,identifier:id});
cache.set(id,mod);if(mod instanceof vm.SourceTextModule)await mod.link((spec,parent)=>load(spec.startsWith('https:')?spec:new URL(spec,'file://'+parent.identifier).pathname));return mod;}
const app=await load(process.cwd()+'/js/app.js');await app.evaluate();await authCb({uid:'admin',email:'tutor@example.com'});
const settle=async()=>{for(let i=0;i<12;i++)await new Promise(setImmediate);};
const navigate=async name=>{window.document.querySelector(`[data-view="${name}"]`).click();await settle();};
test('Ingresar y abrir dashboard no dispara transacciones históricas',async()=>{await settle();assert.equal(transactionCalls,0);assert.ok(!readQueries.some(q=>q.path==='asistencias'));assert.ok(readQueries.filter(q=>q.path==='alumnos').every(q=>q.filters?.some(f=>f.limit===20)));});
test('Interfaz muestra horas cumplidas y planificadas sin errores',async()=>{await navigate('asistencia');window.document.getElementById('btn-sincronizar-asistencia').click();await settle();await navigate('practicas');await window.consultarHorasPractica('p','a');await settle();assert.match(window.document.getElementById('tabla-practicas').textContent,/ULP/);assert.match(window.document.getElementById('tabla-practicas').textContent,/10/);});
test('Todas las secciones administrativas cargan sin alertas de fallo',async()=>{for(const name of ['dashboard','estadisticas','alumnos','informes','resumen','asistencia','notificaciones','usuarios','duplicados','configuracion'])await navigate(name);assert.doesNotMatch(window.document.getElementById('alertas').textContent,/No se pudo cargar la vista/);});
test('Repetir importación no duplica práctica',async()=>{const fileModule=cache.get(process.cwd()+'/js/app.js');await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP',Sector:'Helpdesk',Tipo:'externa','Fecha inicio':'2026-10-01','Fecha fin':'2026-10-02','Hora inicio':'08:00','Hora fin':'13:00','Horas x dia':'5','Dias exactos':'jue,vie',Estado:'programada'}]);const button=window.document.getElementById('btn-importar-confirmar');button.click();await settle();const n=[...store.keys()].filter(k=>k.startsWith('practicas/')).length;await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP',Sector:'Helpdesk',Tipo:'externa','Fecha inicio':'2026-10-01','Fecha fin':'2026-10-02','Hora inicio':'08:00','Hora fin':'13:00','Horas x dia':'5','Dias exactos':'jue,vie',Estado:'programada'}]);button.click();await settle();assert.equal([...store.keys()].filter(k=>k.startsWith('practicas/')).length,n);assert.equal(n,2);});
test('Comprobación gratuita queda en cola y luego muestra el resultado',async()=>{window.document.getElementById('btn-notif-comprobar').click();await settle();const path=[...store.keys()].find(k=>k.startsWith('notificaciones_solicitudes/'));assert.ok(path);assert.equal(store.get(path).solicitanteUid,'admin');assert.equal(store.get(path).accion,'comprobar');assert.match(window.document.getElementById('notif-diagnostico').textContent,/pendiente/);store.set(path,{...store.get(path),estado:'completado',resultado:{listos:0,bloqueados:1,detalles:[{estado:'bloqueado',detalle:'Falta PDF'}]}});window.document.getElementById('btn-notif-actualizar').click();await settle();assert.match(window.document.getElementById('notif-diagnostico').textContent,/Falta PDF/);});
test('Presente no da por realizado un período futuro',async()=>{await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP',Sector:'Helpdesk','Fecha inicio':'2026-10-01','Fecha fin':'2026-10-02','Horas x dia':'5','Dias exactos':'jue,vie',Presente:'si'}]);assert.equal(app.namespace.filasImportar[0].realizada,false);assert.equal(app.namespace.filasImportar[0].horasTotales,10);});
test('Importación de cancelada conserva cancelada',async()=>{await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP',Sector:'Helpdesk','Fecha inicio':'2026-10-01','Fecha fin':'2026-10-02','Horas x dia':'5','Dias exactos':'jue,vie',Estado:'cancelada'}]);assert.equal(app.namespace.filasImportar[0].estado,'cancelada');});
test('Importación requiere días exactos si concurren dos días',async()=>{await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP','Fecha inicio':'2026-10-01','Fecha fin':'2026-10-10','Horas x dia':'5','Dias por semana':'2'}]);assert.ok(app.namespace.filasImportar[0].errores.length);});
test('Importación de realizada sin horas se rechaza',async()=>{await app.namespace.procesarFilasImportar([{Legajo:'123',Lugar:'ULP','Fecha inicio':'2026-09-01',Estado:'realizada'}]);assert.ok(app.namespace.filasImportar[0].errores.length);});
test('Páginas remotas muestran 20, siguiente usa cursor y anterior reutiliza lecturas',async()=>{
 for(let n=0;n<53;n++)store.set('practicas/pagina_'+String(n).padStart(3,'0'),{alumnoId:'a',lugar:'ULP',sector:'Helpdesk',tipo:'externa',fecha:'2026-10-01',fechaFin:'2026-10-02',diasSemana:[4,5],horasPorDia:5});
 await navigate('practicas');window.document.querySelector('#tabla-practicas-remote-nav button:last-child').click();await settle();const table=window.document.getElementById('tabla-practicas');assert.equal(table.querySelectorAll('tr').length,20);const first=[...table.querySelectorAll('[data-practica]')].map(r=>r.dataset.practica);
 const before=readQueries.length;window.document.querySelectorAll('#tabla-practicas-remote-nav button')[1].click();await settle();assert.equal(table.querySelectorAll('tr').length,20);assert.ok(readQueries.slice(before).some(q=>q.filters?.some(f=>f.after)));const second=[...table.querySelectorAll('[data-practica]')].map(r=>r.dataset.practica);assert.ok(second.every(id=>!first.includes(id)));
 const beforeBack=readQueries.length;window.document.querySelector('#tabla-practicas-remote-nav button').click();await settle();assert.equal(readQueries.length,beforeBack);assert.deepEqual([...table.querySelectorAll('[data-practica]')].map(r=>r.dataset.practica),first);
 assert.ok(!readQueries.slice(before).some(q=>q.path==='asistencias'));
 for(let n=0;n<53;n++)store.delete('practicas/pagina_'+String(n).padStart(3,'0'));window.document.querySelector('#tabla-practicas-remote-nav button:last-child').click();await settle();
});
test('Preparar búsqueda mantiene datos y filtro nombre llega a Firestore',async()=>{
 await navigate('configuracion');window.document.getElementById('busqueda-preparar-coleccion').value='alumnos';window.document.getElementById('btn-preparar-busqueda').click();await settle();assert.equal(store.get('alumnos/a').busqueda_nombre,'melissa');assert.equal(store.get('alumnos/a').legajo,'123');
 await navigate('alumnos');window.document.getElementById('alumno-filtro-texto').value='MELÍ';window.document.getElementById('alumno-buscar-campo').value='nombre';const before=readQueries.length;window.document.getElementById('alumno-buscar-campo').dispatchEvent(new window.Event('change'));await settle();assert.match(window.document.getElementById('tabla-alumnos').textContent,/Melissa/);assert.ok(readQueries.slice(before).some(q=>q.filters?.some(f=>f.where?.[0]==='busqueda_nombre')));window.document.getElementById('alumno-filtro-texto').value='';
});
test('Corregir lugar de práctica actualiza filtro de informes sin perder título',async()=>{store.set('informes/cambio_lugar',{practicaId:'p',alumnoId:'a',titulo:'Informe final',lugar:'ULP'});const previous={...store.get('practicas/p')};await app.namespace.guardarPracticaConInformes('p',{...previous,lugar:'Escuela'},previous);assert.equal(store.get('informes/cambio_lugar').lugar,'Escuela');assert.equal(store.get('informes/cambio_lugar').titulo,'Informe final');await app.namespace.guardarPracticaConInformes('p',previous,{...previous,lugar:'Escuela'});store.delete('informes/cambio_lugar');});
test('Preparar asistencia antigua conserva ausencia y horarios al habilitar filtro de estado',async()=>{store.set('asistencias/legacy_estado',{alumnoId:'a',practicaId:'p',fecha:'2026-09-28',presente:false,horaEntrada:'08:30',horaSalida:'12:00'});await navigate('configuracion');window.document.getElementById('busqueda-preparar-coleccion').value='asistencias';window.document.getElementById('btn-preparar-busqueda').click();await settle();const row=store.get('asistencias/legacy_estado');assert.equal(row.estado,'ausente_injustificado');assert.equal(row.presente,false);assert.equal(row.horaEntrada,'08:30');assert.equal(row.tipo,'externa');store.delete('asistencias/legacy_estado');});
test('Cuota al leer perfil muestra el motivo y no abre sesión sin rol',async()=>{docFailure={code:'resource-exhausted'};await authCb({uid:'admin',email:'tutor@example.com'});assert.match(window.document.getElementById('login-error').textContent,/Firestore alcanzó un límite/);assert.ok(window.document.getElementById('app-shell').classList.contains('d-none'));assert.ok(!window.document.getElementById('login-view').classList.contains('d-none'));docFailure=null;});
test.after(()=>dom.window.close());
