import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import crypto from 'node:crypto';
function runtime(){
 let quota=100,mails=[],files=[],download=new Map(),folderError=null,properties=new Map(),triggers=[],counter=0;
 const Utilities={DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],getUuid:()=>String(++counter),formatDate:(d,tz,format)=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));return format==='HH:mm'?p.hour+':'+p.minute:p.year+'-'+p.month+'-'+p.day;}};
 const context=vm.createContext({console,Date,JSON,Utilities,PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty:(k,v)=>properties.set(k,v)})},MailApp:{getRemainingDailyQuota:()=>quota,sendEmail:mail=>{mails.push(mail);quota-=mail.cc?2:1;}},ScriptApp:{getOAuthToken:()=> 'not-a-real-token',getProjectTriggers:()=>triggers,deleteTrigger:t=>triggers=triggers.filter(x=>x!==t),newTrigger:name=>({timeBased(){return this;},everyHours(n){this.hours=n;return this;},create(){const t={getHandlerFunction:()=>name};triggers.push(t);return t;}})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},DriveApp:{getFolderById:()=>{if(folderError)throw Error(folderError);let i=0;return {getId:()=> 'folder',getName:()=> 'Acuerdos',getFolders:()=>({hasNext:()=>false}),getFiles:()=>({hasNext:()=>i<files.length,next:()=>{const f=files[i++];return {getId:()=>f.id,getName:()=>f.name,getMimeType:()=>f.mimeType};}})};},getFileById:id=>({getBlob:()=>({getBytes:()=>[...Buffer.from(download.get(id)||'%PDF-'+id)],setName(name){this.name=name;return this;}})})}});
 for(const file of ['Domain.gs','Firestore.gs','Code.gs'])vm.runInContext(fs.readFileSync('apps-script/'+file,'utf8'),context);
 return {context,mails,setQuota:n=>quota=n,setFiles:f=>files=f,setDownload:(id,v)=>download.set(id,v),setFolderError:s=>folderError=s,getTriggers:()=>triggers,properties};
}
function memory(initial={}){
 const docs=new Map(Object.entries(initial));let revision=0,failResult=false;
 const read=path=>docs.has(path)?{id:path.split('/').pop(),path,updateTime:'t'+revision,data:structuredClone(docs.get(path))}:null;
 const db={get:read,list:(c,w,limit)=>[...docs.keys()].filter(k=>k.startsWith(c+'/')).map(read).filter(r=>!w||w[1]==='EQUAL'?(!w||r.data[w[0]]===w[2]):r.data[w[0]]>=w[2]).slice(0,limit||999999),set:(p,d,merge)=>{docs.set(p,merge?{...docs.get(p),...d}:d);revision++;},write:(p,d,pre,merge)=>({p,d,pre,merge}),commit:writes=>{if(failResult&&writes.some(w=>w.p.startsWith('notificaciones_log/')))throw Error('db failed');writes.forEach(w=>db.set(w.p,w.d,w.merge));},transaction:fn=>{const writes=[];const result=fn({get:read,set:(p,d)=>writes.push({p,d}),update:(p,d)=>writes.push({p,d,merge:true})});db.commit(writes);return result;}};
 return {db,docs,failResult:()=>failResult=true};
}
const now={date:'2026-09-29',time:'14:00'},config={diasAviso:7,horaEnvio:'08:00',acuerdosFolderId:'folder',automatico:true};
const a={id:'a',nombre:'Melissa',apellido:'Barbeito',email:'melissa@example.com'},p={id:'p',alumnoId:'a',lugar:'ULP',sector:'Helpdesk',tipo:'externa',fecha:'2026-09-30',fechaFin:'2026-10-01',diasSemana:[3,4],horaInicio:'08:00',horaFin:'13:00',horasPorDia:5,modoHoras:'jornadas'},file={id:'pdf',name:'melissabarbeito-ulp-helpdesk.pdf',mimeType:'application/pdf'};
const budget=()=>({start:Date.now(),sent:0});
function scenario(){const rt=runtime(),mem=memory({'practicas/p':p,'alumnos/a':a});rt.setFiles([file]);return {...rt,...mem};}
test('Apps Script adjunta el PDF de la práctica al destinatario correcto',()=>{const s=scenario(),r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(r.enviados,1);assert.equal(s.mails[0].to,a.email);assert.equal(s.mails[0].attachments[0].name,file.name);assert.equal(s.docs.get('practicas/p').avisoAutomaticoEnviado,true);});
test('PDF faltante impide enviar',()=>{const s=scenario(),r=s.context.CPbatch(s.db,[p],[a],config,now,[],null,false,budget(),'programado');assert.equal(r.bloqueados,1);assert.equal(s.mails.length,0);});
test('PDF duplicado impide enviar',()=>{const s=scenario(),r=s.context.CPbatch(s.db,[p],[a],config,now,[file,{...file,id:'2'}],null,false,budget(),'programado');assert.equal(r.bloqueados,1);assert.equal(s.mails.length,0);});
test('Word disfrazado de PDF no se envía',()=>{const s=scenario();s.setDownload('pdf','PK Word');const r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(r.bloqueados,1);});
test('PDF de más de ocho MiB se rechaza',()=>{const s=scenario();s.setDownload('pdf','%PDF-'+ 'x'.repeat(8*1024*1024));assert.throws(()=>s.context.CPpdf(file));});
test('Comprobar no envía ni crea intentos',()=>{const s=scenario(),r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,true,budget(),'manual');assert.equal(r.listos,1);assert.equal(s.mails.length,0);assert.equal(s.docs.size,2);});
test('Cuota insuficiente deja pendiente sin reclamar intento',()=>{const s=scenario();s.setQuota(0);const r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(r.pendientes,1);assert.equal(s.mails.length,0);assert.equal(s.docs.size,2);});
test('CC cuenta como otro destinatario para la cuota',()=>{const s=scenario();s.setQuota(1);const r=s.context.CPbatch(s.db,[p],[a],{...config,ccEmail:'tutor@example.com'},now,[file],null,false,budget(),'programado');assert.equal(r.pendientes,1);assert.equal(s.mails.length,0);});
test('CC idéntico no consume un destinatario adicional',()=>{const s=scenario();s.setQuota(1);const r=s.context.CPbatch(s.db,[p],[a],{...config,ccEmail:a.email},now,[file],null,false,budget(),'programado');assert.equal(r.enviados,1);assert.equal(s.mails[0].cc,undefined);});
test('Dos ejecuciones no envían dos veces la misma práctica',()=>{const s=scenario();s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(s.mails.length,1);});
test('Un fallo incierto bloquea el reintento',()=>{const s=scenario();s.context.MailApp.sendEmail=()=>{throw Error('timeout');};const r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(r.detalles[0].estado,'requiere_revision');s.context.MailApp.sendEmail=mail=>s.mails.push(mail);s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(s.mails.length,0);});
test('Fallo de persistencia tras enviar conserva el bloqueo',()=>{const s=scenario();s.failResult();assert.throws(()=>s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado'));assert.equal(s.docs.get('notificaciones_envios/'+s.context.CPkey(p,a)).estado,'enviando');assert.equal(s.mails.length,1);});
test('Cambio concurrente de sector impide enviar el PDF anterior',()=>{const s=scenario();s.docs.set('practicas/p',{...p,sector:'Otro'});const r=s.context.CPbatch(s.db,[p],[a],config,now,[file],null,false,budget(),'programado');assert.equal(r.omitidos,1);assert.equal(s.mails.length,0);});
test('Alumno archivado y práctica cancelada no reciben correo',()=>{const s=scenario();s.context.CPbatch(s.db,[p],[{...a,archivado:true}],config,now,[file],null,false,budget(),'programado');s.context.CPbatch(s.db,[{...p,estado:'cancelada'}],[a],config,now,[file],null,false,budget(),'programado');assert.equal(s.mails.length,0);});
test('Selección manual no envía a otros alumnos',()=>{const s=scenario();const r=s.context.CPbatch(s.db,[p],[a],config,now,[file],['otra'],false,budget(),'manual');assert.equal(r.detalles.length,1);assert.equal(r.detalles[0].estado,'omitido');});
test('La solicitud exige que el solicitante siga siendo docente',()=>{const s=scenario();s.docs.set('usuarios/u',{rol:'alumno'});const req={path:'notificaciones_solicitudes/r',data:{accion:'enviar',solicitanteUid:'u',practicaIds:['p']}};s.docs.set(req.path,req.data);s.context.CPrequest(s.db,req,[p],[a],config,now,[file],budget());assert.equal(s.docs.get(req.path).estado,'error');assert.equal(s.mails.length,0);});
test('Solicitud de comprobación se completa sin enviar',()=>{const s=scenario();s.docs.set('usuarios/u',{rol:'tutor'});const req={path:'notificaciones_solicitudes/r',updateTime:'t',data:{accion:'comprobar',solicitanteUid:'u'}};s.docs.set(req.path,req.data);s.context.CPrequest(s.db,req,[p],[a],config,now,[file],budget());assert.equal(s.docs.get(req.path).estado,'completado');assert.equal(s.docs.get(req.path).resultado.listos,1);assert.equal(s.mails.length,0);});
test('Cuota agotada devuelve la solicitud a pendiente',()=>{const s=scenario();s.setQuota(0);s.docs.set('usuarios/u',{rol:'admin'});const req={path:'notificaciones_solicitudes/r',data:{accion:'enviar',solicitanteUid:'u',practicaIds:['p']}};s.docs.set(req.path,req.data);s.context.CPrequest(s.db,req,[p],[a],config,now,[file],budget());assert.equal(s.docs.get(req.path).estado,'pendiente');});
test('Correo particular se envía con MailApp sin EmailJS',()=>{const s=scenario();s.docs.set('usuarios/u',{rol:'admin'});const req={path:'notificaciones_solicitudes/r',data:{accion:'particular',solicitanteUid:'u',nombre:'Tutor',email:'tutor@example.com',asunto:'Aviso',mensaje:'Mensaje'}};s.docs.set(req.path,req.data);s.context.CPrequest(s.db,req,[p],[a],config,now,[],budget());assert.equal(s.mails[0].to,'tutor@example.com');assert.equal(s.docs.get(req.path).estado,'completado');});
test('La sincronización horaria crea sólo jornadas terminadas y no duplica',()=>{const s=runtime(),q={...p,id:'q',fecha:'2026-09-28',fechaFin:'2026-09-30',diasSemana:[1,2,3]},m=memory({'practicas/q':q});s.context.CPsync(m.db,[q],now,budget());s.context.CPsync(m.db,[q],now,budget());const records=[...m.docs.keys()].filter(k=>k.startsWith('asistencias/'));assert.equal(records.length,2);assert.ok(!records.some(k=>k.includes('2026-09-30')));});
test('Asistencia manual ausente prevalece sobre generación',()=>{const s=runtime(),q={...p,id:'q',fecha:'2026-09-28',fechaFin:'2026-09-28',diasSemana:[1]},id=s.context.CPDomain.attendanceId('q',q.fecha),r={practicaId:'q',alumnoId:'a',fecha:q.fecha,lugar:q.lugar,tipo:q.tipo,estado:'ausente_injustificado',origen:'manual',confirmado:true},m=memory({'practicas/q':q,['asistencias/'+id]:r});s.context.CPsync(m.db,[q],now,budget());assert.equal(m.docs.get('asistencias/'+id).estado,'ausente_injustificado');});
test('La instalación crea un solo disparador horario sin enviar',()=>{const s=scenario();s.context.CPFirestore=()=>s.db;s.context.instalarAvisos();s.context.instalarAvisos();assert.equal(s.getTriggers().length,1);assert.equal(s.mails.length,0);});
test('Una lista de direcciones no pasa como un único email',()=>{const s=runtime();assert.equal(s.context.CPDomain.validEmail('a,b@example.com'),false);});
test('Adaptador REST usa OAuth y serializa campos y máscaras',()=>{const s=runtime(),calls=[];s.context.UrlFetchApp={fetch:(url,opt)=>{calls.push({url,opt});return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({})};}};const db=s.context.CPFirestore('demo');db.set('configuracion/notificaciones',{automatico:true,horas:2,detalles:[{estado:'listo'}]},true);const payload=JSON.parse(calls[0].opt.payload);assert.equal(calls[0].opt.headers.Authorization,'Bearer not-a-real-token');assert.equal(payload.writes[0].update.fields.automatico.booleanValue,true);assert.equal(payload.writes[0].update.fields.horas.integerValue,'2');assert.deepEqual(payload.writes[0].updateMask.fieldPaths,['automatico','horas','detalles']);});
test('Adaptador REST conserva el token en lecturas y commit transaccional',()=>{const s=runtime(),calls=[];s.context.UrlFetchApp={fetch:(url,opt)=>{calls.push({url,opt});const data=url.endsWith(':beginTransaction')?{transaction:'txn'}:url.includes('?transaction=')?{name:'projects/demo/databases/(default)/documents/alumnos/a',fields:{nombre:{stringValue:'Ana'}},updateTime:'v1'}:{};return {getResponseCode:()=>200,getContentText:()=>JSON.stringify(data)};}};const db=s.context.CPFirestore('demo');db.transaction(tx=>{assert.equal(tx.get('alumnos/a').data.nombre,'Ana');tx.update('alumnos/a',{nombre:'Otra'});});assert.match(calls[1].url,/transaction=txn/);assert.equal(JSON.parse(calls[2].opt.payload).transaction,'txn');});

test('Ejecución completa respeta la hora local sin enviar antes',()=>{const s=scenario();s.context.CPFirestore=()=>s.db;s.context.CPDomain.clock=()=>({...now,time:'07:00'});s.docs.set('configuracion/notificaciones',config);s.context.procesarControlPracticas();assert.equal(s.mails.length,0);assert.equal(s.docs.get('configuracion/notificaciones').ultimoControl.motor,'apps_script');});
test('Ejecución completa automática utiliza MailApp después de la hora',()=>{const s=scenario();s.context.CPFirestore=()=>s.db;s.context.CPDomain.clock=()=>now;s.docs.set('configuracion/notificaciones',config);s.context.procesarControlPracticas();assert.equal(s.mails.length,1);assert.equal(s.docs.get('configuracion/notificaciones').ultimoControl.enviados,1);});
test('Error de carpeta se refleja en solicitud de comprobación sin enviar',()=>{const s=scenario();s.context.CPFirestore=()=>s.db;s.context.CPDomain.clock=()=>now;s.setFolderError('No hay acceso');s.docs.set('usuarios/u',{rol:'admin'});s.docs.set('notificaciones_solicitudes/r',{accion:'comprobar',solicitanteUid:'u',estado:'pendiente'});s.context.procesarControlPracticas();assert.equal(s.mails.length,0);assert.match(s.docs.get('notificaciones_solicitudes/r').detalle,/No hay acceso/);});
