import test from 'node:test';
import assert from 'node:assert/strict';
import {inspectNotices,dispatchNotices,noticeKey,validatePdf,publicDetail} from '../functions/notification-engine.mjs';
const now={date:'2026-09-29',time:'09:00'};
const config={diasAviso:3,horaEnvio:'08:00',acuerdosFolderId:'folder',adjuntosConfigurados:true};
const a={id:'a',nombre:'Melissa',apellido:'Barbeito',email:'melissa@example.com'};
const p={id:'p',alumnoId:'a',fecha:'2026-09-30',lugar:'ULP',sector:'Helpdesk',modoHoras:'jornadas'};
const pdf=Buffer.from('%PDF-1.7\nacuerdo');
const file={id:'pdf1',name:'melissabarbeito-ulp-helpdesk.pdf',mimeType:'application/pdf'};
const inspect=(over={})=>inspectNotices({practices:[p],students:[a],config,now,listFiles:async()=>[file],download:async()=>pdf,...over});
const dispatch=(details,over={})=>dispatchNotices({details,claim:async()=>true,recordResult:async()=>{},send:async()=>{},delay:async()=>{},...over});
test('Adjunta el PDF individual y su nombre al correo',async()=>{const [d]=await inspect();assert.equal(d.estado,'listo');assert.equal(d.params.adjunto_nombre,file.name);assert.equal(d.params.adjunto_acuerdo,'data:application/pdf;base64,'+pdf.toString('base64'));assert.equal(publicDetail(d).params,undefined);});
test('Falta PDF bloquea sin enviar',async()=>{let sends=0;const d=await inspect({listFiles:async()=>[]});const r=await dispatch(d,{send:async()=>sends++});assert.equal(sends,0);assert.equal(r.errores,1);});
test('Duplicidad de PDF bloquea sin enviar',async()=>{const [d]=await inspect({listFiles:async()=>[file,{...file,id:'2'}]});assert.equal(d.estado,'bloqueado');});
test('Un Word renombrado no pasa la validación PDF',()=>assert.throws(()=>validatePdf(Buffer.from('PK Word'))));
test('Un PDF de más de ocho MiB se rechaza',()=>{const bytes=Buffer.alloc(8*1024*1024+1);bytes.write('%PDF-');assert.throws(()=>validatePdf(bytes));});
test('Alumno archivado no recibe avisos',async()=>assert.equal((await inspect({students:[{...a,archivado:true}]}))[0].estado,'bloqueado'));
test('Sin configuración de adjunto no se puede enviar',async()=>assert.rejects(()=>inspect({config:{...config,adjuntosConfigurados:false}})));
test('Dos trabajadores sólo envían una vez con claim exclusivo',async()=>{const details=await inspect();let locked=false,sends=0;const opts={claim:async()=>{if(locked)return false;locked=true;return true;},send:async()=>sends++};await Promise.all([dispatch(details,opts),dispatch(details,opts)]);assert.equal(sends,1);});
test('Timeout conserva intento para revisión sin reintento automático',async()=>{let state;const r=await dispatch(await inspect(),{send:async()=>{throw Error('timeout');},recordResult:async(_,s)=>state=s});assert.equal(state,'requiere_revision');assert.equal(r.enviados,0);});
test('Rechazo definitivo se registra como error recuperable',async()=>{let state;await dispatch(await inspect(),{send:async()=>{throw Object.assign(Error('400'),{definiteFailure:true});},recordResult:async(_,s)=>state=s});assert.equal(state,'error');});
test('Si el registro falla después de enviar se propaga y no se libera claim',async()=>{let locked=false,sends=0;const details=await inspect(),opts={claim:async()=>{if(locked)return false;locked=true;return true;},send:async()=>sends++,recordResult:async()=>{throw Error('db');}};await assert.rejects(()=>dispatch(details,opts));await dispatch(details,opts);assert.equal(sends,1);});
test('Cada alumno obtiene su archivo, nunca un adjunto común',async()=>{const b={...a,id:'b',nombre:'Ana',apellido:'Perez',email:'ana@example.com'},q={...p,id:'q',alumnoId:'b'},other={...file,id:'pdf2',name:'anaperez-ulp-helpdesk.pdf'};const details=await inspect({practices:[p,q],students:[a,b],listFiles:async()=>[file,other],download:async id=>Buffer.from('%PDF-'+id)});assert.notEqual(details[0].params.adjunto_acuerdo,details[1].params.adjunto_acuerdo);assert.equal(details[1].params.to_email,b.email);});
test('La prueba de adjuntos no realiza envíos ni escribe registros',async()=>{const d=await inspect();assert.equal(d.length,1);assert.equal(d[0].estado,'listo');});
test('Cambiar práctica, correo o archivo invalida la identidad del intento',()=>{assert.notEqual(noticeKey(p,a),noticeKey({...p,sector:'otro'},a));assert.notEqual(noticeKey(p,a),noticeKey(p,{...a,email:'otro@example.com'}));assert.notEqual(noticeKey(p,a),noticeKey({...p,acuerdoNombre:'otro.pdf'},a));});
test('Selección manual limita destinatarios',async()=>assert.deepEqual(await inspect({ids:['otra']}),[]));
test('PDF faltantes al principio no impiden enviar los acuerdos listos',async()=>{let sends=0;const listo=(await inspect())[0],details=[...Array.from({length:25},(_,i)=>({estado:'bloqueado',practicaId:'f'+i,detalle:'Falta PDF'})),listo];const result=await dispatch(details,{send:async()=>sends++});assert.equal(sends,1);assert.equal(result.enviados,1);});
